"""业务/系统错误码约定：与 HTTP 状态码一致的 3 位码。"""

# 4xx
CODE_BAD_REQUEST = 400
CODE_UNAUTHORIZED = 401
CODE_FORBIDDEN = 403
CODE_NOT_FOUND = 404
CODE_VALIDATION = 422
CODE_RATE_LIMITED = 429

# 兼容旧命名（同值别名，便于业务语义阅读）
CODE_USERNAME_EXISTS = CODE_BAD_REQUEST
CODE_WEAK_PASSWORD_BLACKLIST = CODE_BAD_REQUEST
CODE_WEAK_PASSWORD_COMPLEXITY = CODE_BAD_REQUEST
CODE_WEAK_PASSWORD_CONTAINS_USERNAME = CODE_BAD_REQUEST
CODE_USER_NOT_FOUND = CODE_NOT_FOUND

# 5xx
CODE_INTERNAL = 500
CODE_UNAVAILABLE = 503
